import pc from 'picocolors';
import { getIssue, addLabels, commentOnIssue } from '../github.js';
import { generate } from '../ai.js';

const SYSTEM_PROMPT = `You are a technical issue triage assistant for Strata, a procedural 3D graphics library for React Three Fiber.

Analyze the GitHub issue and determine:
1. Type: bug, feature, enhancement, documentation, question
2. Priority: critical, high, medium, low
3. Complexity: trivial, simple, moderate, complex
4. Whether it can be automated (clear requirements, well-scoped, no design decisions needed)

Keep your response conversational and helpful. Format as:

**Type:** <type>
**Priority:** <priority>  
**Complexity:** <complexity>
**Automatable:** <yes/no>

Then provide a brief analysis and any recommendations.

If the issue is ready for automated development, end with: <!-- ready-for-aider -->`;

export interface AssessOptions {
    dryRun?: boolean;
    verbose?: boolean;
}

export async function assess(issueNumber: number, options: AssessOptions = {}): Promise<void> {
    const { dryRun = false, verbose = false } = options;

    console.log(pc.blue(`Assessing issue #${issueNumber}...`));

    const issue = getIssue(issueNumber);

    if (verbose) {
        console.log(pc.dim(`Title: ${issue.title}`));
        console.log(pc.dim(`Labels: ${issue.labels.join(', ') || 'none'}`));
    }

    const prompt = `Analyze this GitHub issue:

**Title:** ${issue.title}

**Description:**
${issue.body || '(no description provided)'}

**Current Labels:** ${issue.labels.join(', ') || 'none'}`;

    if (verbose) {
        console.log(pc.dim('Analyzing with AI...'));
    }

    const response = await generate(prompt, { systemPrompt: SYSTEM_PROMPT });

    console.log('\n' + pc.green('Assessment:'));
    console.log(response);

    if (dryRun) {
        console.log(pc.yellow('\n[Dry run] Would add comment and labels'));
        return;
    }

    // Extract type from response for labeling
    const typeMatch = response.match(/\*\*Type:\*\*\s*(\w+)/i);
    if (typeMatch) {
        const typeLabel = typeMatch[1].toLowerCase();
        const validLabels = ['bug', 'feature', 'enhancement', 'documentation'];
        if (validLabels.includes(typeLabel) && !issue.labels.includes(typeLabel)) {
            console.log(pc.blue(`\nAdding label: ${typeLabel}`));
            addLabels(issueNumber, [typeLabel]);
        }
    }

    // Check if ready for automation
    if (response.includes('<!-- ready-for-aider -->')) {
        console.log(pc.blue('Adding label: ready-for-aider'));
        addLabels(issueNumber, ['ready-for-aider']);
    }

    // Post comment
    console.log(pc.blue('Posting assessment comment...'));
    commentOnIssue(issueNumber, `## 🤖 AI Triage Assessment\n\n${response}\n\n---\n_Generated by @strata/triage_`);

    console.log(pc.green('Done!'));
}
