import pc from 'picocolors';
import { execFileSync } from 'node:child_process';
import { getIssue, commentOnIssue } from '../github.js';
import { generateWithTools } from '../ai.js';
import { createInlineFilesystemClient, type MCPClient } from '../mcp.js';

const SYSTEM_PROMPT = `You are an expert TypeScript developer working on Strata, a procedural 3D graphics library for React Three Fiber.

Your task is to implement changes based on the GitHub issue provided. You have access to file system tools:
- read_file: Read a file's contents
- write_file: Write content to a file
- list_files: List files in a directory
- search_files: Search for files matching a pattern

Guidelines:
1. First, explore the codebase to understand the structure
2. Read relevant existing files before making changes
3. Make minimal, focused changes that address the issue
4. Follow the existing code style (TypeScript, React functional components)
5. Add proper types - no 'any'
6. Include JSDoc comments for public APIs
7. Handle edge cases (division by zero, null checks)

After making changes, summarize what you did.`;

export interface DevelopOptions {
    dryRun?: boolean;
    verbose?: boolean;
    maxSteps?: number;
}

export async function develop(issueNumber: number, options: DevelopOptions = {}): Promise<void> {
    const { dryRun = false, verbose = false, maxSteps = 10 } = options;

    console.log(pc.blue(`Developing for issue #${issueNumber}...`));

    // Get issue details
    const issue = getIssue(issueNumber);

    if (verbose) {
        console.log(pc.dim(`Title: ${issue.title}`));
    }

    // Get working directory
    const workingDirectory = process.cwd();
    console.log(pc.dim(`Working directory: ${workingDirectory}`));

    let mcpClient: MCPClient | null = null;

    try {
        // Create MCP filesystem client
        console.log(pc.dim('Connecting to filesystem MCP server...'));
        mcpClient = await createInlineFilesystemClient(workingDirectory);

        // Get tools from MCP
        const tools = await mcpClient.tools();
        console.log(pc.dim(`Available tools: ${Object.keys(tools).join(', ')}`));

        // Build prompt
        const prompt = `Implement the following GitHub issue:

**Issue #${issueNumber}: ${issue.title}**

**Description:**
${issue.body || '(no description provided)'}

Start by exploring the codebase structure, then implement the necessary changes.`;

        if (dryRun) {
            console.log(pc.yellow('\n[Dry run] Would execute AI with filesystem tools'));
            console.log(pc.dim('Prompt:'));
            console.log(prompt);
            return;
        }

        console.log(pc.blue('\nStarting AI-powered development...'));

        // Run AI with tools
        const result = await generateWithTools(prompt, tools, {
            systemPrompt: SYSTEM_PROMPT,
        });

        console.log('\n' + pc.green('Development Summary:'));
        console.log(result.text);

        if (result.toolCalls.length > 0) {
            console.log(pc.dim(`\nTool calls made: ${result.toolCalls.length}`));
        }

        // Check if any files were modified
        const writeOps = (result.toolResults as Array<{ toolName?: string }>).filter(
            (r) => r.toolName === 'write_file'
        );

        if (writeOps.length > 0) {
            console.log(pc.green(`\n✅ Modified ${writeOps.length} file(s)`));

            // Stage and commit changes
            console.log(pc.blue('\nStaging changes...'));
            execFileSync('git', ['add', '-A'], { cwd: workingDirectory });

            const status = execFileSync('git', ['status', '--short'], {
                cwd: workingDirectory,
                encoding: 'utf-8',
            });

            if (status.trim()) {
                console.log(pc.dim(status));

                // Commit
                const commitMessage = `feat: implement #${issueNumber} - ${issue.title}

AI-generated implementation for issue #${issueNumber}.

Generated by @strata/triage`;

                execFileSync('git', ['commit', '-m', commitMessage], {
                    cwd: workingDirectory,
                });

                console.log(pc.green('✅ Changes committed'));
            } else {
                console.log(pc.yellow('No changes to commit'));
            }
        } else {
            console.log(pc.yellow('\nNo files were modified'));
        }

        // Comment on issue
        const summary = result.text.length > 1000
            ? result.text.slice(0, 1000) + '...'
            : result.text;

        commentOnIssue(issueNumber, `## 🤖 AI Development Progress

${summary}

---
_Generated by @strata/triage_`);

        console.log(pc.green('\nDone!'));

    } finally {
        if (mcpClient) {
            await mcpClient.close();
        }
    }
}
