import pc from 'picocolors';
import { execFileSync, spawnSync } from 'node:child_process';
import { getIssue, commentOnIssue } from '../github.js';
import { generate } from '../ai.js';

const SYSTEM_PROMPT = `You are a technical project manager for Strata, a procedural 3D graphics library for React Three Fiber.

Your task is to analyze GitHub issues and create actionable project plans. For each issue, you should:

1. **Break down requirements** into clear, testable acceptance criteria
2. **Identify dependencies** on other issues or components
3. **Estimate complexity** and effort
4. **Create sub-tasks** that can be worked on independently
5. **Suggest test requirements** for each task

Format your response as:

## 📋 Project Plan

### Requirements
<numbered list of specific, testable requirements>

### Acceptance Criteria
<checklist format that can be copied to the issue>

### Dependencies
<list of related issues, components, or prerequisites>

### Breakdown

#### Task 1: <name>
- **Effort:** <small/medium/large>
- **Files:** <list of files to modify>
- **Tests:** <test types needed>
- **Description:** <what needs to be done>

#### Task 2: <name>
...

### Suggested Labels
<comma-separated labels>

### Estimated Total Effort
<small/medium/large/epic>`;

export interface PlanOptions {
    dryRun?: boolean;
    verbose?: boolean;
    createTasks?: boolean;
}

export async function plan(issueNumber: number, options: PlanOptions = {}): Promise<void> {
    const { dryRun = false, verbose = false, createTasks = false } = options;

    console.log(pc.blue(`Creating project plan for issue #${issueNumber}...`));

    const issue = getIssue(issueNumber);

    if (verbose) {
        console.log(pc.dim(`Title: ${issue.title}`));
        console.log(pc.dim(`Labels: ${issue.labels.join(', ') || 'none'}`));
    }

    // Get related issues for context
    let relatedIssues = '';
    try {
        const related = execFileSync('gh', ['issue', 'list', '--limit', '10', '--json', 'number,title,labels', '--state', 'open'], {
            encoding: 'utf-8',
        });
        const parsed = JSON.parse(related);
        if (parsed.length > 0) {
            relatedIssues = '\n\n**Related Open Issues:**\n' +
                parsed.map((i: { number: number; title: string }) =>
                    `- #${i.number}: ${i.title}`
                ).join('\n');
        }
    } catch {
        // Ignore if we can't get related issues
    }

    const prompt = `Create a project plan for this GitHub issue:

**Issue #${issueNumber}: ${issue.title}**

**Description:**
${issue.body || '(no description provided)'}

**Current Labels:** ${issue.labels.join(', ') || 'none'}
${relatedIssues}

Analyze this issue and create a comprehensive project plan.`;

    if (verbose) {
        console.log(pc.dim('Analyzing with AI...'));
    }

    const response = await generate(prompt, { systemPrompt: SYSTEM_PROMPT });

    console.log('\n' + pc.green('Project Plan:'));
    console.log(response);

    if (dryRun) {
        console.log(pc.yellow('\n[Dry run] Would post plan as comment'));
        return;
    }

    // Post plan as comment
    console.log(pc.blue('Posting project plan...'));
    commentOnIssue(issueNumber, `${response}\n\n---\n_Generated by @strata/triage_`);

    // Optionally create sub-issues for tasks
    if (createTasks) {
        console.log(pc.blue('Creating sub-task issues...'));

        // Extract tasks from response
        const taskMatches = response.matchAll(/#### Task \d+: (.+?)\n[\s\S]*?- \*\*Description:\*\* (.+?)(?=\n####|\n###|$)/g);

        for (const match of taskMatches) {
            const taskTitle = match[1].trim();
            const taskDesc = match[2].trim();

            try {
                spawnSync('gh', [
                    'issue', 'create',
                    '--title', `[Task] ${taskTitle}`,
                    '--body', `Parent: #${issueNumber}\n\n${taskDesc}\n\n---\n_Auto-created from project plan_`,
                    '--label', 'task'
                ], { encoding: 'utf-8', stdio: 'pipe' });
                console.log(pc.dim(`Created task: ${taskTitle}`));
            } catch (err) {
                console.log(pc.yellow(`Could not create task: ${taskTitle}`));
            }
        }
    }

    console.log(pc.green('Done!'));
}
