import pc from 'picocolors';
import { getPullRequest, commentOnPR } from '../github.js';
import { generate } from '../ai.js';

const SYSTEM_PROMPT = `You are a code reviewer for Strata, a procedural 3D graphics library for React Three Fiber.

Review the pull request and provide feedback on:
1. Code quality and TypeScript best practices
2. Potential bugs, edge cases, division by zero
3. Performance (especially for shaders and rendering)
4. Memory leaks (useEffect cleanup, subscriptions)
5. Security concerns

Be constructive and helpful. Keep responses concise. Format as:

## Summary
<1-2 sentences>

## Score: <1-5>/5 ⭐

## Issues
<bulleted list or "None found">

## Suggestions
<bulleted list of improvements>

## Verdict
<APPROVE, REQUEST_CHANGES, or COMMENT>`;

export interface ReviewOptions {
    dryRun?: boolean;
    verbose?: boolean;
}

export async function review(prNumber: number, options: ReviewOptions = {}): Promise<void> {
    const { dryRun = false, verbose = false } = options;

    console.log(pc.blue(`Reviewing PR #${prNumber}...`));

    const pr = getPullRequest(prNumber);

    if (verbose) {
        console.log(pc.dim(`Title: ${pr.title}`));
        console.log(pc.dim(`Files: ${pr.files.length}`));
    }

    // Truncate large diffs
    const maxDiffSize = 30000;
    const diffPreview = pr.diff.length > maxDiffSize
        ? pr.diff.slice(0, maxDiffSize) + '\n...(truncated)'
        : pr.diff;

    const prompt = `Review this pull request:

**Title:** ${pr.title}

**Description:**
${pr.body || '(no description provided)'}

**Files Changed:** ${pr.files.join(', ')}

**Diff:**
\`\`\`diff
${diffPreview}
\`\`\``;

    if (verbose) {
        console.log(pc.dim('Analyzing with AI...'));
    }

    const response = await generate(prompt, { systemPrompt: SYSTEM_PROMPT });

    console.log('\n' + pc.green('Review:'));
    console.log(response);

    if (dryRun) {
        console.log(pc.yellow('\n[Dry run] Would post review comment'));
        return;
    }

    console.log(pc.blue('Posting review comment...'));
    commentOnPR(prNumber, `${response}\n\n---\n_Generated by @strata/triage_`);

    console.log(pc.green('Done!'));
}
