import pc from 'picocolors';
import { execFileSync } from 'node:child_process';
import { getPullRequest, commentOnPR } from '../github.js';
import { generateWithTools } from '../ai.js';
import { createPlaywrightClient, getPlaywrightTools, type MCPClient } from '../playwright.js';

const SYSTEM_PROMPT = `You are a QA engineer verifying changes for Strata, a procedural 3D graphics library for React Three Fiber.

Your task is to verify that a pull request works correctly by:

1. **Running existing tests** and reporting results
2. **Running E2E verification** in the browser if applicable
3. **Checking for regressions** in related functionality

You have access to Playwright browser automation tools:
- browser_navigate: Navigate to a URL
- browser_click: Click elements
- browser_snapshot: Get page accessibility snapshot
- browser_verify_element_visible: Assert element visibility
- browser_verify_text_visible: Assert text is visible
- browser_take_screenshot: Capture visual state

Guidelines:
- Start by running unit and integration tests
- If there's a dev server, navigate to it and verify visually
- Check for console errors
- Verify the specific functionality mentioned in the PR
- Report any issues found`;

export interface VerifyOptions {
    dryRun?: boolean;
    verbose?: boolean;
    devServerUrl?: string;
}

export async function verify(prNumber: number, options: VerifyOptions = {}): Promise<void> {
    const { dryRun = false, verbose = false, devServerUrl } = options;

    console.log(pc.blue(`Verifying PR #${prNumber}...`));

    const pr = getPullRequest(prNumber);

    if (verbose) {
        console.log(pc.dim(`Title: ${pr.title}`));
        console.log(pc.dim(`Files: ${pr.files.length}`));
    }

    const workingDirectory = process.cwd();

    // Run unit tests first
    console.log(pc.blue('\n1. Running unit tests...'));
    let unitTestResult = '';
    try {
        unitTestResult = execFileSync('pnpm', ['run', 'test'], {
            cwd: workingDirectory,
            encoding: 'utf-8',
            timeout: 300000, // 5 min timeout
        });
        console.log(pc.green('✅ Unit tests passed'));
    } catch (err) {
        unitTestResult = (err as { stdout?: string }).stdout || 'Tests failed';
        console.log(pc.yellow('⚠️ Some unit tests failed'));
    }

    // Run E2E tests
    console.log(pc.blue('\n2. Running E2E tests...'));
    let e2eTestResult = '';
    try {
        e2eTestResult = execFileSync('pnpm', ['run', 'test:e2e'], {
            cwd: workingDirectory,
            encoding: 'utf-8',
            timeout: 300000,
        });
        console.log(pc.green('✅ E2E tests passed'));
    } catch (err) {
        e2eTestResult = (err as { stdout?: string }).stdout || 'E2E tests failed or not configured';
        console.log(pc.yellow('⚠️ E2E tests failed or not available'));
    }

    // If dev server URL provided, do browser verification
    let browserVerification = '';
    let playwrightClient: MCPClient | null = null;

    if (devServerUrl) {
        console.log(pc.blue(`\n3. Browser verification at ${devServerUrl}...`));

        if (dryRun) {
            console.log(pc.yellow('[Dry run] Would verify in browser'));
        } else {
            try {
                playwrightClient = await createPlaywrightClient({
                    headless: true,
                    testingCapabilities: true,
                    outputDir: './verify-output',
                });

                const tools = await getPlaywrightTools(playwrightClient);

                const prompt = `Verify this PR works correctly:

**PR #${prNumber}: ${pr.title}**

**Description:**
${pr.body || '(no description)'}

**Changed Files:** ${pr.files.join(', ')}

Navigate to ${devServerUrl} and verify the changes work correctly.
Take a screenshot and check for any visual issues or console errors.`;

                const result = await generateWithTools(prompt, tools, {
                    systemPrompt: SYSTEM_PROMPT,
                });

                browserVerification = result.text;
                console.log(pc.green('✅ Browser verification complete'));

            } catch (err) {
                browserVerification = `Browser verification failed: ${err instanceof Error ? err.message : err}`;
                console.log(pc.yellow('⚠️ Browser verification failed'));
            } finally {
                if (playwrightClient) await playwrightClient.close();
            }
        }
    }

    // Build verification report
    const report = `## 🔍 Verification Report for PR #${prNumber}

### Unit Tests
\`\`\`
${unitTestResult.slice(-2000)}
\`\`\`

### E2E Tests
\`\`\`
${e2eTestResult.slice(-2000)}
\`\`\`

${browserVerification ? `### Browser Verification\n${browserVerification}\n` : ''}

---
_Generated by @strata/triage_`;

    console.log('\n' + pc.green('Verification Report:'));
    console.log(report.slice(0, 1000) + '...');

    if (dryRun) {
        console.log(pc.yellow('\n[Dry run] Would post verification report'));
        return;
    }

    // Post report
    console.log(pc.blue('\nPosting verification report...'));
    commentOnPR(prNumber, report);

    console.log(pc.green('Done!'));
}
