name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have checked the documentation to confirm this doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to create [specific effect] but can't because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this be used in a 3D scene or application?

  - type: dropdown
    id: preset
    attributes:
      label: Related Preset
      description: Which preset does this relate to?
      options:
        - Core/General
        - Sky
        - Volumetrics
        - Terrain
        - MarchingCubes
        - Water
        - Vegetation
        - Raymarching
        - Character
        - Fur
        - Molecular
        - New preset
        - Other

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      options:
        - "No - new feature"
        - "Maybe - modifies existing APIs"
        - "Yes - breaking change"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this to your project?
      options:
        - Nice-to-have
        - Important
        - Blocking

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've considered?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or references
