/**
 * @jbcom/strata
 *
 * The complete solution for foreground, midground, and background layer
 * 3D gaming in Node.js. Provides terrain, water, vegetation, characters,
 * fur, shells, molecular rendering, and more.
 *
 * Organized into presets for easy integration into your game.
 */

// Core algorithms (pure TypeScript, no React)
export {
    // SDF
    sdSphere,
    sdBox,
    sdPlane,
    sdCapsule,
    sdTorus,
    sdCone,
    opUnion,
    opSubtraction,
    opIntersection,
    opSmoothUnion,
    opSmoothSubtraction,
    opSmoothIntersection,
    noise3D,
    fbm,
    warpedFbm,
    getBiomeAt,
    getTerrainHeight,
    sdCaves,
    sdTerrain,
    sdRock,
    calcNormal,
    // Marching cubes
    marchingCubes,
    createGeometryFromMarchingCubes,
    generateTerrainChunk,
    // Instancing (pure TS)
    generateInstanceData as generateInstanceDataCore,
    createInstancedMesh,
    // Water (pure TS)
    createWaterMaterial,
    createAdvancedWaterMaterial,
    createWaterGeometry,
    // Ray marching (pure TS)
    createRaymarchingMaterial,
    createRaymarchingGeometry,
    // Sky (pure TS)
    createSkyMaterial,
    createSkyGeometry,
    // Volumetrics (pure TS)
    createVolumetricFogMeshMaterial,
    createUnderwaterOverlayMaterial,
    // Clouds (pure TS)
    createCloudLayerMaterial,
    createVolumetricCloudMaterial,
    createCloudLayerGeometry,
    createVolumetricCloudGeometry,
    adaptCloudColorsForTimeOfDay,
    calculateWindOffset,
    fbmNoise2D,
    sampleCloudDensity,
    createDefaultCloudSkyConfig,
    // Particles (pure TS)
    ParticleEmitter as CoreParticleEmitter,
    createParticleEmitter,
    // Weather (pure TS)
    WeatherSystem as CoreWeatherSystem,
    WindSimulation,
    createWeatherSystem,
    createWindSimulation,
    calculateTemperature,
    getPrecipitationType,
    // Camera utilities (pure TS)
    lerp,
    lerpVector3,
    slerp,
    smoothDamp,
    smoothDampVector3,
    CameraShake as CoreCameraShake,
    FOVTransition,
    easeInOutCubic,
    easeOutCubic,
    easeInCubic,
    easeOutElastic,
    evaluateCatmullRom,
    calculateLookAhead,
    calculateHeadBob,
    calculateScreenShakeIntensity,
    // Decals and billboards (pure TS)
    DecalProjector,
    updateBillboardRotation,
    createBillboardMatrix,
    sortBillboardsByDepth,
    createSpriteSheetAnimation,
    updateSpriteSheetAnimation,
    getSpriteSheetUVs,
    applySpriteSheetFrame,
    createSpriteSheetMaterial,
    createDecalTexture,
    createBulletHoleTexture,
    createBloodSplatterTexture,
    createScorchMarkTexture,
    createFootprintTexture,
    createWaterPuddleTexture,
    // LOD (pure TS)
    LODManager,
    calculateLODLevel,
    createLODLevels,
    simplifyGeometry,
    generateLODGeometries,
    createImpostorTexture,
    createImpostorGeometry,
    updateImpostorUV,
    calculateImpostorAngle,
    interpolateLODMaterials,
    createDitherPattern,
    calculateScreenSpaceSize,
    shouldUseLOD,
    createVegetationLODLevels,
    calculateVegetationDensity,
    batchLODObjects,
    // God rays (pure TS)
    createGodRaysMaterial,
    createVolumetricSpotlightMaterial,
    createVolumetricPointLightMaterial,
    createSpotlightConeGeometry,
    createPointLightSphereGeometry,
    calculateRadialBlur,
    calculateSunOcclusion,
    calculateScatteringIntensity,
    getLightScreenPosition,
    calculateGodRayIntensityFromAngle,
    updateGodRaysLightPosition,
    blendGodRayColors,
    // Input (pure TS)
    InputManager,
    InputStateMachine,
    HapticFeedback,
    createInputManager,
    normalizeAxisValue,
    clampAxis,
    axisToAngle,
    axisToMagnitude,
    angleToAxis,
    // Audio (pure TS)
    Howl,
    Howler,
    SoundManager,
    SpatialAudio,
    createSoundManager,
    createSpatialAudio,
    ENVIRONMENT_PRESETS,
    DEFAULT_SPATIAL_CONFIG,
    isAudioContextUnlocked,
    unlockAudioContext,
    setupAutoUnlock,
    getAudioContext,
    suspendAudioContext,
    resumeAudioContext,
    // Physics (pure TS)
    CollisionLayer,
    collisionFilters,
    calculateImpulse,
    calculateForce,
    calculateJumpImpulse,
    calculateLandingVelocity,
    applyDrag,
    calculateBuoyancyForce,
    calculateSlopeAngle,
    isWalkableSlope,
    projectVelocityOntoGround,
    calculateSteeringAngle,
    calculateSuspensionForce,
    calculateExplosionForce,
    generateDebrisVelocity,
    createDefaultPhysicsConfig,
    createDefaultCharacterConfig,
    createDefaultVehicleConfig,
    createHumanoidRagdoll,
    createDefaultDestructibleConfig,
    createDefaultBuoyancyConfig,
    // Post-Processing utilities (pure TS)
    calculateFocusDistance,
    calculateFocusDistanceToMesh,
    focalLengthToFOV,
    fovToFocalLength,
    apertureToBokehScale,
    dofScenarios,
    defaultEffectSettings,
    lutConfigs,
    blendPostProcessingPresets,
    getTimeOfDayEffects,
    // Animation (pure TS)
    FABRIKSolver,
    CCDSolver,
    TwoBoneIKSolver,
    LookAtController,
    SpringDynamics,
    SpringChain,
    ProceduralGait,
    createBoneChain,
    createBoneChainFromLengths,
    clampAngle,
    dampedSpring,
    dampedSpringVector3,
    hermiteInterpolate,
    sampleCurve,
    calculateBoneRotation,
    // State management (pure TS)
    createGameStore,
    createPersistenceAdapter,
    calculateChecksum,
    verifyChecksum,
    webPersistenceAdapter,
    createWebPersistenceAdapter,
    create,
    useStore,
    temporal,
    immer,
    // UI utilities (pure TS)
    getAnchorOffset,
    worldToScreen,
    screenToWorld,
    calculateFade,
    formatProgressText,
    clampProgress,
    uiLerp,
    uiEaseOutCubic,
    uiEaseOutElastic,
    getTextDirection,
    createDefaultProgressBar,
    createDefaultInventory,
    createDefaultDialog,
    createDefaultTooltip,
    createDefaultNotification,
    createDefaultMinimap,
    createDefaultCrosshair,
    createDefaultDamageNumber,
    createDefaultNameplate,
    getDamageNumberColor,
    formatNumber,
    getNotificationIcon,
    getNotificationColor,
} from './core';
export type {
    // SDF types
    SDFBiomeData,
    // Instancing types (same InstanceData, different BiomeData)
    InstanceData,
    InstancingBiomeData,
    // Marching cubes types
    MarchingCubesResult,
    MarchingCubesOptions,
    TerrainChunk,
    // Particle types
    ParticleEmitterConfig,
    EmissionShape,
    ParticleForces,
    ParticleBehavior,
    EmitterShapeParams,
    // Weather types
    WeatherType,
    WeatherStateConfig,
    WeatherTransition,
    WindConfig,
    TemperatureConfig,
    // Camera types
    CameraShakeConfig,
    FOVTransitionConfig,
    CameraPath,
    ScreenShakeIntensity,
    // Cloud types
    CloudLayerConfig,
    WindConfig as CloudWindConfig,
    DayNightConfig,
    CloudMaterialOptions,
    VolumetricCloudOptions,
    CloudSkyConfig,
    // Decal types
    DecalProjectorConfig,
    DecalInstance,
    BillboardConfig,
    SpriteSheetConfig,
    SpriteAnimationState,
    // LOD types
    LODLevel,
    LODConfig,
    LODState,
    ImpostorConfig,
    SimplificationOptions,
    VegetationLODConfig,
    // God rays types
    GodRaysMaterialOptions,
    VolumetricSpotlightMaterialOptions,
    VolumetricPointLightMaterialOptions,
    RadialBlurOptions,
    OcclusionResult,
    ScatteringParams,
    // Input types
    DragState,
    InputAxis,
    InputEvent,
    HapticPattern,
    GamepadState,
    PointerState,
    InputManagerConfig,
    // Audio types
    AudioConfig,
    SoundConfig,
    SpatialConfig,
    AudioBus,
    AudioMixer,
    DistanceModel,
    AudioFormat,
    EnvironmentPreset,
    EnvironmentEffectConfig,
    AudioListenerState,
    // Physics types
    PhysicsConfig,
    CollisionFilter,
    CharacterControllerConfig,
    VehicleConfig,
    WheelConfig,
    RagdollJointConfig,
    RagdollBodyPart,
    RagdollConfig,
    PhysicsMaterial,
    DestructibleConfig,
    BuoyancyConfig,
    // Post-Processing types
    PostProcessingMood,
    PostProcessingPreset,
    BloomSettings,
    DOFSettings,
    VignetteSettings,
    ChromaticAberrationSettings,
    FilmGrainSettings,
    ColorGradingSettings,
    SSAOSettings,
    ToneMappingSettings,
    NoiseSettings,
    BrightnessContrastSettings,
    SepiaSettings,
    LUTConfig,
    // Animation types
    BoneChain,
    BoneConstraint,
    IKSolverResult,
    SpringConfig,
    SpringState,
    GaitConfig,
    GaitState,
    LookAtConfig,
    LookAtState,
    // State management types
    GameStore,
    GameStoreApi,
    GameStoreState,
    GameStoreActions,
    StoreConfig,
    SaveData,
    CheckpointData,
    CheckpointOptions,
    PersistenceAdapter,
    StateChangeType,
    StateChangeEvent,
    StateListener,
    AutoSaveConfig,
    // UI types
    UIAnchor,
    TextDirection,
    ProgressBarConfig,
    InventorySlot,
    InventoryConfig,
    DialogLine,
    DialogChoice,
    DialogConfig,
    TooltipConfig,
    NotificationConfig,
    MinimapConfig,
    MinimapMarker,
    CrosshairConfig,
    DamageNumberConfig,
    NameplateConfig,
    ScreenPosition,
} from './core';

// React components
export {
    Water,
    AdvancedWater,
    GPUInstancedMesh,
    GrassInstances,
    TreeInstances,
    RockInstances,
    generateInstanceData,
    ProceduralSky,
    createTimeOfDay,
    CloudLayer,
    CloudSky,
    VolumetricClouds,
    VolumetricEffects,
    VolumetricFogMesh,
    UnderwaterOverlay,
    EnhancedFog,
    Raymarching,
    ParticleEmitter,
    ParticleBurst,
    Rain,
    Snow,
    Lightning,
    WeatherEffects,
    // Camera components
    FollowCamera,
    OrbitCamera,
    FPSCamera,
    CinematicCamera,
    CameraShake,
    useCameraTransition,
    // Decal components
    Decal,
    Billboard,
    AnimatedBillboard,
    DecalPool,
    // LOD components
    LODMesh,
    LODGroup,
    Impostor,
    LODVegetation,
    // God rays components
    GodRays,
    LightShafts,
    VolumetricSpotlight,
    VolumetricPointLight,
    // Input components
    Joystick3D,
    GroundSwitch,
    PressurePlate,
    WallButton,
    TriggerComposer,
    // AI components (YukaJS integration)
    YukaEntityManager,
    YukaVehicle,
    YukaPath,
    YukaStateMachine,
    YukaNavMesh,
    useYukaContext,
    yukaVector3ToThree,
    threeVector3ToYuka,
    syncYukaToThree,
    // Audio components
    AudioProvider,
    AudioListener,
    PositionalAudio,
    AmbientAudio,
    AudioZone,
    AudioEmitter,
    AudioEnvironment,
    FootstepAudio,
    WeatherAudio,
    useAudioContext,
    useAudioManager,
    // Physics components
    CharacterController,
    VehicleBody,
    Destructible,
    Buoyancy,
    Ragdoll,
    // Post-Processing components
    EffectStack,
    CinematicEffects,
    DreamyEffects,
    HorrorEffects,
    NeonEffects,
    RealisticEffects,
    VintageEffects,
    DynamicDOF,
    MotionBlurEffect,
    // Animation components
    IKChain,
    IKLimb,
    LookAt,
    SpringBone,
    ProceduralWalk,
    HeadTracker,
    TailPhysics,
    BreathingAnimation,
    BlinkController,
    // State management components
    GameStateProvider,
    GameStateContext,
    useGameStateContext,
    useGameState,
    useSaveLoad,
    useUndo,
    useCheckpoint,
    useAutoSave,
    PersistGate,
    StateDebugger,
    // UI components
    HealthBar,
    Nameplate,
    DamageNumber,
    ProgressBar3D,
    Inventory,
    Tooltip,
    DialogBox,
    Notification,
    Minimap,
    Crosshair,
    // Shader components
    ToonMesh,
    HologramMesh,
    DissolveMesh,
    Forcefield,
    Outline,
    GradientMesh,
    GlitchMesh,
    CrystalMesh,
} from './components';

// Presets (organized by layer: background, midground, foreground)
export * from './presets';
export type {
    // Re-export InstanceData from components (same as core)
    InstanceData as ComponentInstanceData,
    // Re-export BiomeData from components (same as core InstancingBiomeData)
    BiomeData as ComponentBiomeData,
    // Component-specific types
    TimeOfDayState,
    WeatherState,
    // Particle component types
    ParticleEmitterProps,
    ParticleEmitterRef,
    ParticleBurstProps,
    // Weather component types
    RainProps,
    SnowProps,
    LightningProps,
    WeatherSystemProps,
    // Cloud component types
    CloudLayerProps,
    CloudSkyProps,
    VolumetricCloudsProps,
    // Camera component types
    FollowCameraProps,
    FollowCameraRef,
    OrbitCameraProps,
    OrbitCameraRef,
    FPSCameraProps,
    FPSCameraRef,
    CinematicCameraProps,
    CinematicCameraRef,
    CameraShakeProps,
    CameraShakeRef,
    CameraTransitionProps,
    // Decal component types
    DecalProps,
    DecalRef,
    BillboardProps,
    BillboardRef,
    AnimatedBillboardProps,
    AnimatedBillboardRef,
    DecalPoolProps,
    DecalPoolRef,
    // LOD component types
    LODMeshProps,
    LODMeshRef,
    LODGroupProps,
    LODGroupRef,
    ImpostorProps,
    ImpostorRef,
    LODVegetationProps,
    LODVegetationRef,
    // God rays component types
    GodRaysProps,
    GodRaysRef,
    VolumetricSpotlightProps,
    VolumetricSpotlightRef,
    VolumetricPointLightProps,
    VolumetricPointLightRef,
    // Input component types
    InputControlRef,
    InputControlEvents,
    Joystick3DProps,
    Joystick3DRef,
    GroundSwitchProps,
    GroundSwitchRef,
    PressurePlateProps,
    PressurePlateRef,
    WallButtonProps,
    WallButtonRef,
    TriggerShape,
    TriggerBehavior,
    TriggerConfig,
    TriggerMaterialConfig,
    TriggerBehaviorConfig,
    TriggerComposerProps,
    TriggerComposerRef,
    // AI component types
    YukaEntityManagerContextValue,
    YukaEntityManagerProps,
    YukaVehicleProps,
    YukaVehicleRef,
    YukaPathProps,
    YukaPathRef,
    StateConfig,
    YukaStateMachineProps,
    YukaStateMachineRef,
    YukaNavMeshProps,
    YukaNavMeshRef,
    // Audio component types
    AudioContextValue,
    AudioProviderProps,
    AudioListenerProps,
    PositionalAudioProps,
    PositionalAudioRef,
    AmbientAudioProps,
    AmbientAudioRef,
    AudioZoneProps,
    AudioZoneRef,
    AudioEmitterProps,
    AudioEmitterRef,
    AudioEnvironmentProps,
    FootstepAudioProps,
    FootstepAudioRef,
    WeatherAudioProps,
    // Physics component types
    CharacterControllerProps,
    CharacterControllerRef,
    VehicleBodyProps,
    VehicleBodyRef,
    DestructibleProps,
    DestructibleRef,
    BuoyancyProps,
    BuoyancyRef,
    RagdollProps,
    RagdollRef,
    // Post-Processing component types
    EffectStackProps,
    CinematicEffectsProps,
    DreamyEffectsProps,
    HorrorEffectsProps,
    NeonEffectsProps,
    RealisticEffectsProps,
    VintageEffectsProps,
    DynamicDOFProps,
    DynamicDOFRef,
    MotionBlurEffectProps,
    // Animation component types
    IKChainProps,
    IKChainRef,
    IKLimbProps,
    IKLimbRef,
    LookAtProps,
    LookAtRef,
    SpringBoneProps,
    SpringBoneRef,
    ProceduralWalkProps,
    ProceduralWalkRef,
    HeadTrackerProps,
    HeadTrackerRef,
    TailPhysicsProps,
    TailPhysicsRef,
    BreathingAnimationProps,
    BreathingAnimationRef,
    BlinkControllerProps,
    BlinkControllerRef,
    // State management component types
    GameStateContextValue,
    GameStateProviderProps,
    UseSaveLoadOptions,
    UseSaveLoadReturn,
    UseUndoReturn,
    UseCheckpointReturn,
    UseAutoSaveOptions,
    UseAutoSaveReturn,
    PersistGateProps,
    StateDebuggerProps,
    GameStoreApi as ComponentGameStoreApi,
    GameStore as ComponentGameStore,
    CheckpointData as ComponentCheckpointData,
    AutoSaveConfig as ComponentAutoSaveConfig,
    StateChangeEvent as ComponentStateChangeEvent,
    // UI component types
    HealthBarProps,
    HealthBarRef,
    NameplateProps,
    NameplateRef,
    DamageNumberProps,
    ProgressBar3DProps,
    InventoryProps,
    InventoryRef,
    TooltipProps,
    DialogBoxProps,
    DialogBoxRef,
    NotificationProps,
    MinimapProps,
    CrosshairProps,
    // Shader component types
    ToonMeshProps,
    ToonMeshRef,
    HologramMeshProps,
    HologramMeshRef,
    DissolveMeshProps,
    DissolveMeshRef,
    ForcefieldProps,
    ForcefieldRef,
    OutlineProps,
    GradientMeshProps,
    GradientMeshRef,
    GlitchMeshProps,
    GlitchMeshRef,
    CrystalMeshProps,
    CrystalMeshRef,
} from './components';

// Hooks
export {
    useSeek,
    useFlee,
    useArrive,
    usePursue,
    useEvade,
    useWander,
    useFollowPath,
    useSeparation,
    useAlignment,
    useCohesion,
    useObstacleAvoidance,
    useOffsetPursuit,
    useInterpose,
} from './hooks';
export type {
    UseSeekOptions,
    UseFleeOptions,
    UseArriveOptions,
    UsePursueOptions,
    UseEvadeOptions,
    UseWanderOptions,
    UseFollowPathOptions,
    UseSeparationOptions,
    UseAlignmentOptions,
    UseCohesionOptions,
    UseObstacleAvoidanceOptions,
    UseOffsetPursuitOptions,
    UseInterposeOptions,
} from './hooks';

// GLSL shaders
export * from './shaders';

// Utilities
export * from './utils';
