/**
 * Unit test setup file
 *
 * Mocks WebGL and DOM APIs for tests that don't need real rendering
 */

// Mock WebGL context for Three.js
if (typeof document !== 'undefined') {
    // Create a minimal WebGL mock (always use mock in test environment)
    const mockGL: Record<string, unknown> = {
        VERSION: 0x1f02,
        SHADING_LANGUAGE_VERSION: 0x8b8c,
        VENDOR: 0x1f00,
        RENDERER: 0x1f01,
        getParameter: function (param: number) {
            // VERSION should return a string
            if (param === 0x1f02) return 'WebGL 1.0 (Mock)'; // VERSION
            if (param === 0x8b8c) return 'GLSL ES 1.0 (Mock)'; // SHADING_LANGUAGE_VERSION
            if (param === 0x1f00) return 'Mock Vendor'; // VENDOR
            if (param === 0x1f01) return 'Mock Renderer'; // RENDERER
            return 0;
        },
        getExtension: () => null,
        getContextAttributes: () => ({
            alpha: true,
            antialias: true,
            depth: true,
            failIfMajorPerformanceCaveat: false,
            powerPreference: 'default',
            premultipliedAlpha: true,
            preserveDrawingBuffer: false,
            stencil: true,
            xrCompatible: false,
        }),
        getSupportedExtensions: () => [],
        createShader: () => ({}),
        shaderSource: () => {},
        compileShader: () => {},
        getShaderParameter: () => true,
        createProgram: () => ({}),
        attachShader: () => {},
        linkProgram: () => {},
        getProgramParameter: (program: unknown, pname: number) => {
            // Return 0 for ACTIVE_UNIFORMS and ACTIVE_ATTRIBUTES to avoid iteration
            if (pname === 35718 || pname === 35721) return 0; // ACTIVE_UNIFORMS, ACTIVE_ATTRIBUTES
            return true;
        },
        getActiveUniform: () => ({ name: 'u_test', type: 5126, size: 1 }),
        getActiveAttrib: () => ({ name: 'a_test', type: 5126, size: 1 }),
        useProgram: () => {},
        createBuffer: () => ({}),
        bindBuffer: () => {},
        bufferData: () => {},
        enableVertexAttribArray: () => {},
        vertexAttribPointer: () => {},
        drawArrays: () => {},
        viewport: () => {},
        clearColor: () => {},
        clear: () => {},
        clearDepth: () => {},
        clearStencil: () => {},
        enable: () => {},
        disable: () => {},
        blendFunc: () => {},
        depthFunc: () => {},
        depthMask: () => {},
        colorMask: () => {},
        stencilMask: () => {},
        stencilFunc: () => {},
        stencilOp: () => {},
        stencilFuncSeparate: () => {},
        stencilOpSeparate: () => {},
        stencilMaskSeparate: () => {},
        cullFace: () => {},
        frontFace: () => {},
        getUniformLocation: () => ({}),
        getAttribLocation: () => 0,
        uniform1i: () => {},
        uniform1f: () => {},
        uniform2f: () => {},
        uniform3f: () => {},
        uniform4f: () => {},
        uniform1fv: () => {},
        uniform2fv: () => {},
        uniform3fv: () => {},
        uniform4fv: () => {},
        uniformMatrix3fv: () => {},
        uniformMatrix4fv: () => {},
        activeTexture: () => {},
        bindTexture: () => {},
        texImage2D: () => {},
        texParameteri: () => {},
        generateMipmap: () => {},
        pixelStorei: () => {},
        createTexture: () => ({}),
        deleteTexture: () => {},
        deleteShader: () => {},
        deleteProgram: () => {},
        deleteBuffer: () => {},
        createFramebuffer: () => ({}),
        bindFramebuffer: () => {},
        framebufferTexture2D: () => {},
        checkFramebufferStatus: () => 36053, // FRAMEBUFFER_COMPLETE
        deleteFramebuffer: () => {},
        createRenderbuffer: () => ({}),
        bindRenderbuffer: () => {},
        renderbufferStorage: () => {},
        framebufferRenderbuffer: () => {},
        deleteRenderbuffer: () => {},
        drawElements: () => {},
        drawBuffers: () => {},
        readPixels: () => {},
        scissor: () => {},
        getShaderInfoLog: () => '',
        getProgramInfoLog: () => '',
        isContextLost: () => false,
        FRAGMENT_SHADER: 35632,
        VERTEX_SHADER: 35633,
        ARRAY_BUFFER: 34962,
        ELEMENT_ARRAY_BUFFER: 34963,
        STATIC_DRAW: 35044,
        DYNAMIC_DRAW: 35048,
        TRIANGLES: 4,
        TRIANGLE_STRIP: 5,
        TRIANGLE_FAN: 6,
        LINES: 1,
        LINE_STRIP: 3,
        POINTS: 0,
        TEXTURE_2D: 3553,
        TEXTURE_CUBE_MAP: 34067,
        TEXTURE_WRAP_S: 10242,
        TEXTURE_WRAP_T: 10243,
        TEXTURE_MIN_FILTER: 10241,
        TEXTURE_MAG_FILTER: 10240,
        CLAMP_TO_EDGE: 33071,
        REPEAT: 10497,
        NEAREST: 9728,
        LINEAR: 9729,
        NEAREST_MIPMAP_NEAREST: 9984,
        LINEAR_MIPMAP_NEAREST: 9985,
        NEAREST_MIPMAP_LINEAR: 9986,
        LINEAR_MIPMAP_LINEAR: 9987,
        RGB: 6407,
        RGBA: 6408,
        UNSIGNED_BYTE: 5121,
        UNSIGNED_SHORT: 5123,
        UNSIGNED_INT: 5125,
        FLOAT: 5126,
        COLOR_BUFFER_BIT: 16384,
        DEPTH_BUFFER_BIT: 256,
        STENCIL_BUFFER_BIT: 1024,
        DEPTH_TEST: 2929,
        BLEND: 3042,
        CULL_FACE: 2884,
        LEQUAL: 515,
        LESS: 513,
        DEPTH_COMPONENT: 6402,
        DEPTH_COMPONENT16: 33189,
        TEXTURE0: 33984,
        UNPACK_FLIP_Y_WEBGL: 37440,
        UNPACK_PREMULTIPLY_ALPHA_WEBGL: 37441,
        FRAMEBUFFER: 36160,
        RENDERBUFFER: 36161,
        COLOR_ATTACHMENT0: 36064,
        DEPTH_ATTACHMENT: 36096,
        FRAMEBUFFER_COMPLETE: 36053,
        MAX_TEXTURE_SIZE: 3379,
        MAX_CUBE_MAP_TEXTURE_SIZE: 34076,
        MAX_VERTEX_ATTRIBS: 34921,
        MAX_VARYING_VECTORS: 36348,
        MAX_VERTEX_UNIFORM_VECTORS: 36347,
        MAX_FRAGMENT_UNIFORM_VECTORS: 36349,
        ACTIVE_UNIFORMS: 35718,
        ACTIVE_ATTRIBUTES: 35721,
        LINK_STATUS: 35714,
        COMPILE_STATUS: 35713,
        SRC_ALPHA: 770,
        ONE_MINUS_SRC_ALPHA: 771,
        ONE: 1,
        ZERO: 0,
        FRONT: 1028,
        BACK: 1029,
        CCW: 2305,
        CW: 2304,
    };

    // Mock 2D context for canvas operations
    const mock2D = {
        fillRect: () => {},
        clearRect: () => {},
        getImageData: () => ({ data: new Uint8ClampedArray(4) }),
        putImageData: () => {},
        createImageData: () => ({ data: new Uint8ClampedArray(4) }),
        setTransform: () => {},
        drawImage: () => {},
        save: () => {},
        restore: () => {},
        beginPath: () => {},
        moveTo: () => {},
        lineTo: () => {},
        closePath: () => {},
        stroke: () => {},
        fill: () => {},
        translate: () => {},
        scale: () => {},
        rotate: () => {},
        arc: () => {},
        measureText: () => ({ width: 0 }),
        fillText: () => {},
        strokeText: () => {},
        createLinearGradient: () => ({
            addColorStop: () => {},
        }),
        createRadialGradient: () => ({
            addColorStop: () => {},
        }),
        createPattern: () => ({}),
        canvas: { width: 300, height: 150 },
    };

    // Override getContext to return mocks
    const originalGetContext = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (contextType: string) {
        if (contextType === 'webgl' || contextType === 'webgl2') {
            return mockGL as unknown as WebGLRenderingContext;
        }
        if (contextType === '2d') {
            return mock2D as unknown as CanvasRenderingContext2D;
        }
        return originalGetContext.call(this, contextType);
    };
}
